name: EmbeddedCI
on:
  push:
    paths:
      - "scenario-bmp280-stm32/**"

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Submit job to EmbeddedCI
        uses: embeddedci-com/submit-job-action@main
        with:
          api_url: ${{ secrets.EMBEDDEDCI_API_URL }}
          api_key: ${{ secrets.EMBEDDEDCI_API_KEY }}
          source_path: scenario-bmp280-stm32

